import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/contexts/ModalContext";
import EstimateModal from "@/components/EstimateModal";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Empire Asphalt Paving",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} antialiased`}
      >
        <ModalProvider>
          {children}
          <EstimateModal />
        </ModalProvider>
      </body>
    </html>
  );
}
